build(deps-dev): bump @types/node from 24.6.2 to 24.9.1 (#768)
* build(deps-dev): bump @types/node from 24.6.2 to 24.9.1

Bumps [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node) from 24.6.2 to 24.9.1.
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node)

---
updated-dependencies:
- dependency-name: "@types/node"
  dependency-version: 24.9.1
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* refactor(browser): fix type error

Error: src/browser.ts(3,36): error TS2345: Argument of type 'SubtleCrypto' is not assignable to parameter of type 'import("crypto").webcrypto.SubtleCrypto'.
  Type 'SubtleCrypto' is missing the following properties from type 'SubtleCrypto': decapsulateBits, decapsulateKey, encapsulateBits, encapsulateKey, getPublicKey

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Mark <mark@remarkablemark.org>