refactor(browser): fix type error
Error: src/browser.ts(3,36): error TS2345: Argument of type 'SubtleCrypto' is not assignable to parameter of type 'import("crypto").webcrypto.SubtleCrypto'.
  Type 'SubtleCrypto' is missing the following properties from type 'SubtleCrypto': decapsulateBits, decapsulateKey, encapsulateBits, encapsulateKey, getPublicKey